const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  ANALYST: "ANALYST",
  EMPLOYEE: "EMPLOYEE",
  CLIENT: "CLIENT",
};

const CLIENT_RESPONSE = {
  ACCEPT: "ACCEPT",
  REJECT: "REJECT",
};

const ALLOCATIONS = {
  PERCENTAGE: "PERCENTAGE",
  QUANTITY: "QUANTITY",
};

const STOCK_CALL_TYPES = {
  BUY: "BUY",
  SELL: "SELL",
};

const MARKET_CALL_TYPES = {
  INTRADAY: "INTRADAY",
  SHORT_TERM: "SHORT_TERM",
  LONG_TERM: "LONG_TERM",
};

const CLIENT_TYPE = {
  DISCRETIONARY: "DISCRETIONARY",
  NON_DISCRETIONARY: "NON_DISCRETIONARY",
};

const RESPONSE_STATUS = {
  INITIATED: "INITIATED",
  COMPLETE: "ACCEPTED",
  REJECTED: "REJECTED",
};

const TASK_STATUS = {
  PENDING: "PENDING",
  COMPLETE: "COMPLETE",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
};

const STOCK_CHANGE_STATE = {
  ADD: "ADD",
  REMOVE: "REMOVE",
  EDIT: "EDIT",
};

const NOTIFICATION_TYPES = {
  NEW_SUBSCRIBER: "NEW_SUBSCRIBER",
  MARKETCALL_UPDATE: "MARKETCALL_UPDATE",
};

module.exports = {
  roleTypes: Object.keys(ROLES),
  clientResponses: Object.keys(CLIENT_RESPONSE),
  allocations: Object.keys(ALLOCATIONS),
  marketCallTypes: Object.keys(MARKET_CALL_TYPES),
  stockCallTypes: Object.keys(STOCK_CALL_TYPES),
  clientTypes: Object.keys(CLIENT_TYPE),
  responseStatus: Object.keys(RESPONSE_STATUS),
  taskStatus: Object.keys(TASK_STATUS),
  stockChangeTypes: Object.keys(STOCK_CHANGE_STATE),
  notificationTypes: Object.keys(NOTIFICATION_TYPES),
  STOCK_CHANGE_STATE,
  CLIENT_RESPONSE,
  ROLES,
  MARKET_CALL_TYPES,
  STOCK_CALL_TYPES,
  CLIENT_TYPE,
  RESPONSE_STATUS,
  TASK_STATUS,
  NOTIFICATION_TYPES
};
