version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build checks...
      - npm audit --production || true
  build:
    commands:
      - echo Build step - Nothing to build for Node.js backend
  post_build:
    commands:
      - echo Preparing deployment package...
      - rm -rf node_modules

artifacts:
  files:
    - '**/*'
  exclude_patterns:
    - 'node_modules/**'
    - '.git/**'
    - '*.log'

cache:
  paths:
    - node_modules/**/*
