const MODULES = require("./enums/modules.config");

module.exports = [
  MODULES.USERS,
  MODULES.ORGANIZATION,
  MODULES.PROFILE,
  MODULES.AUTH,
  MODULES.MARKETCALL,
  MODULES.PROFILEMARKETCALL,
  MODULES.RESPONSE,
  MODULES.MARKETDATA,
  MODULES.TASK,
  MODULES.CALL,
  MODULES.PREDICTRAM,
  MODULES.STOCK,
  MODULES.MARKETCALL_HISTORY,
  MODULES.MARKETCALLPORTFOLIO,
  MODULES.NOTIFICATION,
  MODULES.KYC,
];
